version: '3.3'
services:
    nodejs_listener:
        build:
              context: nodejs/
              dockerfile: Dockerfile
        container_name: nodejsListener
        volumes:
            - audio-volume:/audio
        networks:
            container-network:
                aliases:
                    - nodejsListener
        ports:
            - 5001:5001
        restart: always
    python_manager:
        build:
            context: python/
            dockerfile: Dockerfile
        container_name: pythonManager
        volumes:
            - ./python:/python/
            - audio-volume:/audio
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
        restart: always
        depends_on: 
            - nodejs_listener
        networks:
            container-network:
                aliases:
                    - pythonManager
        ports:
            - 5000:5000
networks:
    container-network:

volumes:
    audio-volume: 