version: '3.3'

networks:
    container-network:

volumes:
    audio-volume: 

services:
    nodejs-listener:
        build:
              context: nodejs/
              dockerfile: Dockerfile
        container_name: nodejs-listener
        volumes:
            - audio-volume:/audio
        networks:
            container-network:
        ports:
            - 5001:5001
        restart: always
    python-manager:
        build:
            context: python/
            dockerfile: Dockerfile
        container_name: python-manager
        volumes:
            - ./python:/python/
            - audio-volume:/audio
        environment:
            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8
        restart: always
        networks:
            container-network:
                aliases:
                    - python-manager
        ports:
            - 5000:5000